default: &default
  adapter: postgresql
  encoding: unicode
  username: organizer
  password: Dg63zBEsAwxyPt4t
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: organizer_development
test:
  <<: *default
  database: organizer_development_test
production:
  <<: *default
  database: organizer_development