default: &default
  adapter: postgresql
  encoding: unicode
  username: organizer
  password: Dg63zBEsAwxyPt4t
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: organizer_development
test:
  <<: *default
  database: organizer_development_test
production:
  adapter: postgresql
  encoding: utf8
  database: d3okd00rb78g18
  username: sbvsxppwldjfdt
  password: 150dda1f42fd92c6babe82e6a0005a71cae0f9424bfd2ae9413953cefe66e4d6
  host: ec2-54-147-209-121.compute-1.amazonaws.com
  sslmode: require
  port: 5432